### ISSUE TITLE
Rolling CF to 235 and got a failure

### ISSUE THREAD

**Issue by fraenkel** [cloudfoundry/nats-release#3]
```
[2016-07-07 19:34:25+0000] ------------ STARTING nats_ctl at Thu Jul  7 19:34:25 UTC 2016 --------------
[2016-07-07 19:34:26+0000] panic: runtime error: slice bounds out of range
[2016-07-07 19:34:26+0000] 
[2016-07-07 19:34:26+0000] goroutine 28 [running]:
[2016-07-07 19:34:27+0000] panic(0x842c20, 0xc820012030)
[2016-07-07 19:34:27+0000] 	/var/vcap/data/packages/golang1.6/85a489b7c0c2584aa9e0a6dd83666db31c6fc8e8.1-89b07798b9c317fefdcf6fcf74789d23025e8281/src/runtime/panic.go:464 +0x3e6
[2016-07-07 19:34:27+0000] github.com/apcera/gnatsd/server.(*client).parse(0xc8203f7000, 0xc82076a000, 0x1d1e, 0x8000, 0x0, 0x0)
[2016-07-07 19:34:27+0000] 	/var/vcap/packages/gnatsd/src/github.com/apcera/gnatsd/server/parser.go:401 +0x1174
[2016-07-07 19:34:27+0000] github.com/apcera/gnatsd/server.(*client).readLoop(0xc8203f7000)
[2016-07-07 19:34:27+0000] 	/var/vcap/packages/gnatsd/src/github.com/apcera/gnatsd/server/client.go:147 +0x199
[2016-07-07 19:34:27+0000] created by github.com/apcera/gnatsd/server.(*client).initClient
[2016-07-07 19:34:27+0000] 	/var/vcap/packages/gnatsd/src/github.com/apcera/gnatsd/server/client.go:125 +0x33a
```

It goes into a loop and never stops.

**Comment by fraenkel** [comment]
This was addressed in https://github.com/nats-io/gnatsd/issues/63

**Comment by jaresty** [comment]
Hi @fraenkel. We saw the PR to bump gnatsd to v0.8.1. We're going to try to get to that work soon. Once that's merged, we'll close this issue.

@jaresty && @dsabeti 
CF Release Integration

**Comment by APShirley** [comment]
It has been merged, this issue should be resolved so we are going to close it.

Thanks,

Al & @jaresty
